### ISSUE TITLE
Design scaffolding for home page

### ISSUE THREAD

**Issue by TylerNakamura** [TylerNakamura/im-telling-the-story#4]
This issue seeks to determine what the home page looks like. Without writing any code, draw some boxes and get a rough outline, for our first draft of the home page.

This could literally be sketches on the back of a napkin. Don't do any code yet. We will create a coding based issue in the next task.

**Comment by TylerNakamura** [comment]
THIS IS ONLY A FIRST DRAFT. Don't worry about making a serious committment here

**Comment by Zarkana** [comment]
Sounds good

**Comment by TylerNakamura** [comment]
maybe you could place the picture in /README.md? That way we can spruce up our readme page :)

**Comment by Zarkana** [comment]
Indeed, will do.

**Comment by Zarkana** [comment]
Accept my branch merge
